---
- name: Converge
  hosts: all
  vars:
    user_id: chris
    unixuser_rclocal_lines:
      - export MY_TEST_VAR=ansible
    unixuser_zshenv_lines:
      - export MY_FILE=zshenv
    unixuser_pub_ssh_keys:
      - https://github.com/cultclassik.keys
    unixuser_apt_pkgs:
      - netcat
      - jq
    unixuser_p10k_file_content: "#!/bin/zsh"

  tasks:
    - name: "Include unixuser"
      ansible.builtin.include_role:
        name: "ansible-role-unixuser"
