---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu
    image: ubuntu:20.04
    env:
      OBCJ_DISABLE_INITIALIZE_FORK_SAFETY: "YES"

provisioner:
  name: ansible
  env:
    OBCJ_DISABLE_INITIALIZE_FORK_SAFETY: "YES"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
