---
# do this for bash as well - .bash_profile?
- name: Write .zshrc.local config
  ansible.builtin.blockinfile:
    path: "~{{ unixuser_user_id }}/.zshrc.local"
    create: yes
    owner: "{{ unixuser_user_id }}"
    group: "{{ unixuser_group_name }}"
    mode: u=rw,g=r,o=r
    marker: "# {mark} ---------------- ANSIBLE MANAGED BLOCK - zshrc local file entries"
    block: |
      {% for line in unixuser_rclocal_lines %}
      {{ line }}
      {% endfor %}
  when: unixuser_rclocal_lines is defined

- name: Write .tmux.conf
  ansible.builtin.blockinfile:
    path: "~{{ unixuser_user_id }}/.tmux.conf"
    create: yes
    owner: "{{ unixuser_user_id }}"
    group: "{{ unixuser_group_name }}"
    mode: u=rw,g=r,o=r
    marker: "# {mark} ---------------- ANSIBLE MANAGED BLOCK - tmux conf file entries"
    block: |
      {% for line in tmux_conf_lines %}
      {{ line }}
      {% endfor %}
  when: tmux_conf_lines is defined
