---
# do this for bash as well - .bash_profile?
- name: Write .zshrc.local block
  ansible.builtin.blockinfile:
    path: "~{{ unixuser_user_id }}/.zshrc.local"
    create: yes
    owner: "{{ unixuser_user_id }}"
    group: "{{ unixuser_group_name }}"
    mode: u=rw,g=r,o=r
    marker: "# {mark} ---------------- ANSIBLE MANAGED BLOCK - zshrc local file entries"
    block: |
      {% for line in unixuser_rclocal_lines %}
      {{ line }}
      {% endfor %}
  when: unixuser_rclocal_lines is defined

- name: Write .zshenv config block
  ansible.builtin.blockinfile:
    path: "~{{ unixuser_user_id }}/.zshenv"
    create: yes
    owner: "{{ unixuser_user_id }}"
    group: "{{ unixuser_group_name }}"
    mode: u=rw,g=r,o=r
    marker: "# {mark} ---------------- ANSIBLE MANAGED BLOCK - zshenv file entries"
    block: |
      {% for line in unixuser_zshenv_lines %}
      {{ line }}
      {% endfor %}
  when: unixuser_zshenv_lines is defined

# $ZDOTDIR/.zshenv
# $ZDOTDIR/.zprofile
# $ZDOTDIR/.zshrc
#

# $ZDOTDIR/.zlogin
# $ZDOTDIR/.zlogout
