---
- name: Manage user account
  ansible.builtin.user:
    state: present
    create_home: True
    name: "{{ unixuser_user_id }}"
    groups: "{{ unixuser_xtra_groups }}"
    append: True
    shell: "{{ unixuser_shell | default('/bin/zsh') }}"
  tags: [ base ]

- name: Debian specific
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
  tags: [ base ]

- name: OSX specific
  ansible.builtin.include_tasks: osx.yml
  when: ansible_os_family == 'Darwin'
  tags: [ base ]

- name: SSH keys
  ansible.builtin.include_tasks: ssh_keys.yml
  tags: [ ssh ]

- name: Antigen
  ansible.builtin.include_tasks: antigen.yml
  tags: [ antigen ]

- name: Powerlevel 10k
  ansible.builtin.include_tasks: powerlevel10k.yml
  tags: [ antigen, p10k ]

- name: dot files
  ansible.builtin.include_tasks: dotfiles.yml
  tags: [ base, dot ]
