---
- name: Ensure user fonts folder exits
  ansible.builtin.file:
    path: "{{ unixuser_font_folder }}"
    owner: "{{ unixuser_user_id }}"
    group: "{{ unixuser_group_name }}"
    mode: u=rwx,g=rx,o=rx
    state: directory

- name: Install Meso fonts
  ansible.builtin.get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/{{ item | urlencode }}"
    dest: "{{ unixuser_font_folder }}/{{ item }}"
    owner: "{{ unixuser_user_id }}"
    group: "{{ unixuser_group_name }}"
    mode: u=rw,g=r,o=r
  loop:
    - 'MesloLGS NF Regular.ttf'
    - 'MesloLGS NF Bold.ttf'
    - 'MesloLGS NF Italic.ttf'
    - 'MesloLGS NF Bold Italic.ttf'
  notify: Update font cache

- name: Create Powerlevel 10k config
  ansible.builtin.copy:
    content: "{{ unixuser_p10k_file_content }}"
    dest: "~{{ unixuser_user_id }}/.p10k.zsh"
    owner: "{{ unixuser_user_id }}"
    group: "{{ unixuser_group_name }}"
    mode: u=rw,g=r,o=r
  when: unixuser_p10k_file_content is defined

# this is already conditionally sourced in the .zshrc template included in this role
# - name: Add p10k to .zshrc.local
#   when: unixuser_profile_env_vars is defined
#   lineinfile:
#     path: "~{{ unixuser_user_id }}/.zshrc.local"
#     line: "source ~/.p10k.zsh # line added by ansible"
#     insertafter: EOF
#     create: yes
#     owner: "{{ unixuser_user_id }}"
#     group: "{{ unixuser_group_name }}"
#     mode: u=rw,g=r,o=r

# add to ~/.zshrc_local for p10k auto prompt:
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi
