---
- name: Add ssh public keys
  ansible.posix.authorized_key:
    user: "{{ unixuser_user_id }}"
    state: present
    key: "{{ user_pub_ssh_key }}"
  loop: "{{ unixuser_user_pub_ssh_keys }}"
  when: unixuser_user_pub_ssh_keys is defined

- name: Distribute ssh private keys
  ansible.builtin.copy:
    content: "{{ item.value }}" #| base64 --decode }}"
    dest: "~{{ unixuser_user_id }}/.ssh/{{ item.key }}"
    owner: "{{ unixuser_user_id }}"
    group: "{{ unixuser_primary_group }}"
    mode: 0600
  with_dict: "{{ unixuser_ssh_private_keys }}"
  # no_log: true
  when: unixuser_ssh_private_keys is defined
