name: Ansible Release
on:
  workflow_run:
    workflows:
      - 'Ansible CI'
    branches:
      - main
    types:
      - completed

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    uses: Diehlabs/shared-workflows/.github/workflows/github-release.yml@v0.2.3
    secrets: inherit
